In [1]:
import torch

In [55]:
class SSVI(torch.nn.Module):
  def __init__(self):
    super().__init__()

    self.a = torch.nn.parameter.Parameter(torch.Tensor([0.]))
    self.b = torch.nn.parameter.Parameter(torch.Tensor([0.]))
    self.c = torch.nn.parameter.Parameter(torch.Tensor([0.]))    

  def forward(self, x):
      return self.a + self.b * x + self.c * x*x


In [123]:
ssvi = SSVI()

x = torch.Tensor([-1,0.,1])

y = torch.Tensor([1,0,1])

#optimizer = torch.optim.Adam(ssvi.parameters(), lr=0.1)
optimizer = torch.optim.SGD(ssvi.parameters(), lr=0.25)



In [126]:
for i in range(10):
    optimizer.zero_grad()

    output = ssvi.forward(x)
    print(output)
    loss = torch.norm(output-y.detach().clone().detach())
    loss.backward()
    optimizer.step()
    print(y.grad)

tensor([1.3750, 0.2186, 1.3750], grad_fn=<AddBackward0>)
None
tensor([ 0.6259, -0.2036,  0.6259], grad_fn=<AddBackward0>)
None
tensor([1.3757, 0.2162, 1.3757], grad_fn=<AddBackward0>)
None
tensor([ 0.6265, -0.2055,  0.6265], grad_fn=<AddBackward0>)
None
tensor([1.3761, 0.2146, 1.3761], grad_fn=<AddBackward0>)
None
tensor([ 0.6268, -0.2068,  0.6268], grad_fn=<AddBackward0>)
None
tensor([1.3764, 0.2136, 1.3764], grad_fn=<AddBackward0>)
None
tensor([ 0.6271, -0.2076,  0.6271], grad_fn=<AddBackward0>)
None
tensor([1.3766, 0.2129, 1.3766], grad_fn=<AddBackward0>)
None
tensor([ 0.6272, -0.2082,  0.6272], grad_fn=<AddBackward0>)
None


In [146]:
ssvi = SSVI()

x = torch.tensor([-1,0.,1])

y = torch.tensor([2.,0.,2.], requires_grad=True)

optimizer = torch.optim.LBFGS(ssvi.parameters(), lr=0.05)

In [148]:
for i in range(1):
    def closure():
        print(y.grad)
        optimizer.zero_grad()        
        output = ssvi.forward(x)    
        loss = torch.norm(output-y)
        loss.backward()
        return loss
    optimizer.step(closure)

tensor([ -1.6040, -10.8230,  -1.6040])
tensor([ -2.2257, -10.3466,  -2.2257])
tensor([-2.7734, -9.7142, -2.7734])
tensor([-3.2275, -8.9476, -3.2275])
tensor([-3.5715, -8.0740, -3.5715])
tensor([-3.7933, -7.1244, -3.7933])
tensor([-3.8836, -6.1326, -3.8836])
tensor([-3.8382, -5.1347, -3.8382])
tensor([-3.6594, -4.1672, -3.6594])
tensor([-3.3526, -3.2662, -3.3526])
tensor([-2.9287, -2.4659, -2.9287])
tensor([-2.4044, -1.7949, -2.4044])
tensor([-1.7983, -1.2797, -1.7983])
tensor([-1.1327, -0.9420, -1.1327])
tensor([-0.4336, -0.7919, -0.4336])
tensor([ 0.2727, -0.8366,  0.2727])
tensor([ 0.9595, -1.0751,  0.9595])
tensor([ 1.6006, -1.4967,  1.6006])
tensor([ 2.1674, -2.0946,  2.1674])
tensor([ 2.6492, -2.8265,  2.6492])


In [149]:
output = ssvi.forward(x)
print(output)

tensor([2.0000e+00, 3.2079e-06, 2.0000e+00], grad_fn=<AddBackward0>)


In [157]:
A = torch.zeros(size=(3,3))

for j,jt in enumerate(ssvi.parameters()):
    for i,it in enumerate(output):
        dx, = torch.autograd.grad(it, jt, create_graph=True, retain_graph=True, allow_unused=True)
        A[i,j] = dx

In [158]:
torch.inverse(A)

tensor([[ 0.0000,  1.0000,  0.0000],
        [-0.5000,  0.0000,  0.5000],
        [ 0.5000, -1.0000,  0.5000]])

In [135]:
ssvi.a.grad

tensor([1.4875])

In [144]:
output = ssvi.forward(x)
loss = torch.norm(output-y)
loss.backward()
optimizer.step()
y.grad

TypeError: step() missing 1 required positional argument: 'closure'