In [16]:
import torch

In [17]:
s = torch.nn.Parameter(torch.tensor([2.],requires_grad=True))
u = torch.nn.Parameter(torch.tensor([3.]))

In [18]:
class BaseModel(torch.nn.Module):
    def __init__(self):
        super().__init__()     
        self.parameterList = torch.nn.ParameterList()

In [19]:
b = BaseModel()

In [20]:
b.parameterList.append(s)
b.parameterList.append(u)

ParameterList(
    (0): Parameter containing: [torch.FloatTensor of size 1]
    (1): Parameter containing: [torch.FloatTensor of size 1]
)

In [21]:
b.named_parameters()

<generator object Module.named_parameters at 0x000002A25545DC78>

In [22]:
for name, param in b.named_parameters():
    print(name)
    print(param)
    print(param.name)
    print(param.data)
    print(param.grad)

parameterList.0
Parameter containing:
tensor([2.], requires_grad=True)
None
tensor([2.])
None
parameterList.1
Parameter containing:
tensor([3.], requires_grad=True)
None
tensor([3.])
None


In [60]:
d = b.parameterList[0] * b.parameterList[1] * b.parameterList[1]

In [61]:
#d.backward()

In [62]:
dd = torch.autograd.grad(d, b.parameters(),create_graph=True, retain_graph=True, allow_unused=True)

In [63]:
for it in dd:
    ddd = torch.autograd.grad(it, b.parameters(), allow_unused=True, retain_graph=True)
    print(ddd)

(None, tensor([6.]))
(tensor([6.]), tensor([4.]))
