In [12]:
import torch

In [2]:
class SSVI(torch.nn.Module):
  def __init__(self):
    super().__init__()

    self.a = torch.nn.parameter.Parameter(torch.Tensor([0.]))
    self.b = torch.nn.parameter.Parameter(torch.Tensor([0.]))
    self.c = torch.nn.parameter.Parameter(torch.Tensor([0.]))    

  def forward(self, x):
      return self.a + self.b * x + self.c * x*x


In [3]:
ssvi = SSVI()

x = torch.Tensor([-1,0.,1])

y = torch.Tensor([1,0,1])

#optimizer = torch.optim.Adam(ssvi.parameters(), lr=0.1)
optimizer = torch.optim.SGD(ssvi.parameters(), lr=0.25)



In [4]:
for i in range(10):
    optimizer.zero_grad()

    output = ssvi.forward(x)
    print(output)
    loss = torch.norm(output-y.detach().clone().detach())
    loss.backward()
    optimizer.step()
    print(y.grad)

tensor([0., 0., 0.], grad_fn=<AddBackward0>)
None
tensor([0.7071, 0.3536, 0.7071], grad_fn=<AddBackward0>)
None
tensor([1.0826, 0.4602, 1.0826], grad_fn=<AddBackward0>)
None
tensor([0.6663, 0.1308, 0.6663], grad_fn=<AddBackward0>)
None
tensor([1.2809, 0.4048, 1.2809], grad_fn=<AddBackward0>)
None
tensor([ 0.6072, -0.0213,  0.6072], grad_fn=<AddBackward0>)
None
tensor([1.3234, 0.3416, 1.3234], grad_fn=<AddBackward0>)
None
tensor([ 0.6072, -0.0913,  0.6072], grad_fn=<AddBackward0>)
None
tensor([1.3455, 0.2981, 1.3455], grad_fn=<AddBackward0>)
None
tensor([ 0.6117, -0.1339,  0.6117], grad_fn=<AddBackward0>)
None


In [5]:
ssvi = SSVI()

x = torch.tensor([-1,0.,1])

y = torch.tensor([2.,0.,2.], requires_grad=True)

optimizer = torch.optim.LBFGS(ssvi.parameters(), lr=0.05)

In [6]:
for i in range(1):
    def closure():
        print(y.grad)
        optimizer.zero_grad()        
        output = ssvi.forward(x)    
        loss = torch.norm(output-y)
        loss.backward()
        return loss
    optimizer.step(closure)

None
tensor([0.7071, -0.0000, 0.7071])
tensor([ 1.4142, -0.0091,  1.4142])
tensor([ 2.0799, -0.3463,  2.0799])
tensor([ 2.5525, -1.0901,  2.5525])
tensor([ 2.9713, -1.8958,  2.9713])
tensor([ 3.3515, -2.7390,  3.3515])
tensor([ 3.6573, -3.6407,  3.6573])
tensor([ 3.8347, -4.6087,  3.8347])
tensor([ 3.8691, -5.6075,  3.8691])
tensor([ 3.7880, -6.6009,  3.7880])
tensor([ 3.6030, -7.5660,  3.6030])
tensor([ 3.3073, -8.4744,  3.3073])
tensor([ 2.8988, -9.2907,  2.8988])
tensor([ 2.3922, -9.9883,  2.3922])
tensor([  1.8076, -10.5509,   1.8076])
tensor([  1.1629, -10.9617,   1.1629])
tensor([  0.4764, -11.2012,   0.4764])
tensor([ -0.2296, -11.2574,  -0.2296])
tensor([ -0.9309, -11.1295,  -0.9309])


In [7]:
output = ssvi.forward(x)
print(output)

tensor([ 2.0026, -0.0020,  2.0026], grad_fn=<AddBackward0>)


In [8]:
A = torch.zeros(size=(3,3))

for j,jt in enumerate(ssvi.parameters()):
    for i,it in enumerate(output):
        dx, = torch.autograd.grad(it, jt, create_graph=True, retain_graph=True, allow_unused=True)
        A[i,j] = dx

In [9]:
torch.inverse(A)

tensor([[ 0.0000,  1.0000,  0.0000],
        [-0.5000,  0.0000,  0.5000],
        [ 0.5000, -1.0000,  0.5000]])

In [10]:
ssvi.a.grad

tensor([1.0397])

In [11]:
output = ssvi.forward(x)
loss = torch.norm(output-y)
loss.backward()
optimizer.step()
y.grad

TypeError: step() missing 1 required positional argument: 'closure'